project4/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('htmx_list_service/<str:service_type>/', views.htmx_list_service, name='htmx_list_service'),
    path('filter-bookings/', views.filter_bookings, name='filter_bookings'),
    path('review-list/', views.review_list, name='review_list'),
    path('reply-review/<int:review_id>/', views.reply_review, name='reply_review'),
    path('flight-filter/', views.filter_flights, name='filter_flights'),
    path('tour-filter/', views.filter_tours, name='filter_tours'),
    path('hotel-filter/', views.filter_hotels, name='filter_hotels'),
    path('create-user/', views.create_user, name='create_user'),
    path('user-detail/<int:user_id>/', views.user_detail, name='user_detail'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete-user/<int:user_id>/', views.user_delete, name='user_delete'),
]

project4/flight/urls.py
from django.urls import path
from . import views

app_name = 'flight'

urlpatterns = [
    path('', views.flight_list, name='flight_list'),
    path('flight/<int:id>/', views.flight_detail, name='flight_detail'),
]

project4/hotel/urls.py
from django.urls import path
from . import views

app_name = 'hotel'

urlpatterns = [
    path('', views.hotel_list, name='hotel_list'),
    path('book/<int:hotel_id>/', views.book_hotel, name='book_hotel'),
    path('detail/<int:id>/', views.hotel_detail, name='hotel_detail')
]

project4/project4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index
from userprofile.forms import LoginForm
from userprofile.views import signup
from userprofile.views import logout_view


urlpatterns = [
    path('', index, name='index'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', logout_view, name='logout'),
    path('sign-up/', signup, name='signup'),
    path('admin/', admin.site.urls, name='admin'),
    path('userprofile/', include('userprofile.urls')),
    path('flight/', include('flight.urls')),
    path('tour/', include('tour.urls')),
    path('hotel/', include('hotel.urls')),
    path('booking/', include('booking.urls')),
    path('promotion/', include('promotion.urls')),
    path('invoice/', include('invoice.urls')),
    path('payment/', include('payment.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project4/tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'

urlpatterns = [
    path('', views.tour_list, name='tour_list'),
    path('book/<int:tour_id>/', views.book_tour, name='book_tour'),
    path('detail/<int:id>/', views.tour_detail, name='tour_detail')
]

project4/dashboard/models.py
from django.db import models

# Create your models here.

project4/flight/models.py
from django.db import models
from datetime import datetime, timedelta
# from django.utils.timezone import now


# Create your models here.
class Flight(models.Model):
    airline = models.CharField(max_length=50)
    flight_date = models.DateField()
    flight_time = models.TimeField()
    departure_city = models.CharField(max_length=20)
    arrival_city = models.CharField(max_length=20)
    duration = models.DecimalField(max_digits=4, decimal_places=2)
    total_seats = models.IntegerField()
    booked_seats = models.IntegerField(default=0)     
    fare = models.DecimalField(max_digits=5, decimal_places=2)

    def calculate_arrival_datetime(self):
        # Convert duration to a timedelta
        # Note: duration is assumed to be in hours
        duration_hours = int(self.duration)
        duration_minutes = int((self.duration - duration_hours) * 60)
        duration_td = timedelta(hours=duration_hours, minutes=duration_minutes)

        # Combine the flight_date and flight_time into a datetime
        departure_datetime = datetime.combine(self.flight_date, self.flight_time)

        # Calculate the arrival datetime
        arrival_datetime = departure_datetime + duration_td
        return arrival_datetime
    
    def available_seats(self):
        """Returns the number of available seats on the flight."""
        return self.total_seats - self.booked_seats
    
    def __str__(self):
        return f'{self.airline} Flight from {self.departure_city} to {self.arrival_city}'

project4/hotel/models.py
from django.db import models
from datetime import timedelta
from datetime import datetime

# Create your models here.
class Hotel(models.Model):
    name = models.CharField(max_length=30)
    city = models.CharField(max_length=20)
    country = models.CharField(max_length=20)
    total_rooms = models.IntegerField()
    nightly_rate = models.DecimalField(max_digits=5, decimal_places=2)
    
    def __str__(self):
        return f"{self.name} in {self.city}, Rooms: {self.total_rooms}, Price: {self.nightly_rate}"

project4/tour/models.py
from django.db import models
from datetime import timedelta, datetime

# Create your models here.
class Tour(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=50)
    destination = models.CharField(max_length=30)
    date = models.DateField()
    time = models.TimeField()
    duration = models.IntegerField()
    max_guests = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)

    def get_end_time(self):
        start_datetime = datetime.combine(self.date, self.time)
        end_datetime = start_datetime + timedelta(hours=self.duration)
        return end_datetime.time()
    
    def __str__(self):
        return f"{self.name} - {self.description[:50]}... on {self.date}"

project4/hotel/forms.py
from django import forms
from .models import Hotel

class HotelBookingForm(forms.Form):
    check_in_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    check_out_date = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    number_of_guests = forms.IntegerField(min_value=1)

    class Meta:
        model = Hotel
        fields = ['check_in_date', 'check_out_date', 'number_of_guests']

project4/tour/forms.py
from django import forms
from .models import Tour

class TourBookingForm(forms.ModelForm):
    class Meta:
        model = Tour
        fields = ['name', 'description', 'destination', 'date', 'time', 'duration', 'max_guests', 'price']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})
        }

project4/dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import  login_required
from booking.models import Booking
from tour.models import Tour
from hotel.models import Hotel
from flight.models import Flight
from review.models import Review
from django.db.models import Avg, OuterRef, Subquery
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import HttpResponse
from userprofile.models import Userprofile
from django.contrib import messages
from django.views.decorators.http import require_http_methods
from django.core.files.storage import default_storage

# Create your views here.

@login_required
def index(request):
    tours = Tour.objects.all()
    hotels = Hotel.objects.all()
    flights = Flight.objects.all()
    bookings = Booking.objects.all()

    context = {
        'tours': tours,
        'hotels': hotels,
        'flights': flights,
        'bookings': bookings
    }
    return render(request, 'dashboard/agent_dashboard.html', context)

@login_required
def htmx_list_service(request, service_type):
    tours = Tour.objects.all()
    hotels = Hotel.objects.all()
    flights = Flight.objects.all()
    bookings = Booking.objects.all()
    booking_status = Booking.BOOKING_STATUS_CHOICES
    booking_context = {
        'bookings': bookings,
        'booking_status': booking_status
    }

    if service_type=='flight':
        flights = Flight.objects.all()
        return render(request, 'partials/dashboard_flight.html', {'flights': flights})
    elif service_type=='hotel':
        return render(request, 'partials/dashboard_hotel.html', {'hotels': hotels})
    elif service_type=='tour':
        return render(request, 'partials/dashboard_tour.html', {'tours': tours})
    else:
        return render(request, 'partials/dashboard_booking.html', {'booking_context': booking_context})
    
@login_required
def filter_bookings(request):
    status = request.GET.get('status', 'all')
    if status != 'all':
        bookings = Booking.objects.filter(status=status)
    else:
        bookings = Booking.objects.all()
    booking_context={
        'bookings': bookings,
    }
    return render(request, 'partials/booking_results.html', {'booking_context': booking_context})
    
@login_required
def review_list(request):
    reviews = Review.objects.all()
    return render(request, 'partials/dashboard_review.html', {'reviews': reviews})

@login_required
def reply_review(request, review_id):
    if request.method != 'POST':
        return HttpResponseBadRequest("Invalid method")
    
    rev = Review.objects.get(id=review_id)
    reply_text = request.POST.get('reply-comment')

    if not reply_text:
        return HttpResponseBadRequest("Reply text is required")

    Review.objects.create(
        user=request.user,
        rating=0,
        comment=reply_text,
        content_type=rev.content_type,
        object_id=rev.object_id,
        parent=rev
    )

    if 'HX-Request' in request.headers:
        # Return only the partial HTML needed to update the page
        return render(request, 'partials/review_replies.html', {'replies': rev.replies.all()})
    else:
        # Redirect back to a full page that shows the review, typically the review detail page
        return HttpResponseRedirect(reverse('dashboard:index'))

@login_required
def filter_flights(request):
    sort = request.GET.get('select', '1')
    flights = None

    if sort == '2':
        flights = Flight.objects.all().order_by('-flight_date')
    elif sort == '3':
        flights = Flight.objects.all().order_by('flight_date')
    else:
        flights = Flight.objects.all()

    return render(request, 'partials/flights_table.html', {'flights': flights})

@login_required
def filter_tours(request):
    sort = request.GET.get('select', '1')
    tours = None

    if sort == '2':
        tours = Tour.objects.all().order_by('-price')
    elif sort == '3':
        tours = Tour.objects.all().order_by('price')
    else:
        tours = Tour.objects.all()

    return render(request, 'partials/tours_table.html', {'tours': tours})

@login_required
def filter_hotels(request):
    sort = request.GET.get('select', '1')
    hotels = None

    if sort == '2':
        hotel_content_type = ContentType.objects.get_for_model(Hotel)
        reviews = Review.objects.filter(
            content_type=hotel_content_type,
            object_id=OuterRef('pk')  
        ).values('object_id').annotate(avg_rating=Avg('rating')).values('avg_rating')

        hotels = Hotel.objects.annotate(
            average_rating=Subquery(reviews[:1])  # Ensures it fetches the avg rating per hotel
        ).order_by('-average_rating')
    elif sort == '3':
        hotels = Hotel.objects.all().order_by('-total_rooms')
    else:
        hotels = Hotel.objects.all()

    return render(request, 'partials/hotels_table.html', {'hotels': hotels})

@login_required
def create_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = User.objects.create_user(username=username, password=password)
    user.save()
    users = User.objects.all()
    return render(request, 'partials/user_table.html', {'users': users})

@login_required
def user_detail(request, user_id):
    user = get_object_or_404(User, id=user_id)
    return render(request, 'dashboard/dashboard_user_detail.html', {'user': user})

@login_required
def edit_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method == 'POST':
        user.username = request.POST.get('username')
        user.email = request.POST.get('email')
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.save()
        user.userprofile
        user.userprofile.street_address = request.POST.get('street_address')
        user.userprofile.city = request.POST.get('city')
        user.userprofile.state = request.POST.get('state')
        user.userprofile.zipcode = request.POST.get('zipcode')
        user.userprofile.phone_number = request.POST.get('phone_number')
        user.userprofile.save()
        messages.success(request, 'User updated successfully')
        return HttpResponse('User updated successfully')
    
@login_required
def user_delete(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.delete()
    return redirect(reverse('dashboard:index'))

project4/flight/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Flight
from review.models import Review
from django.contrib.contenttypes.models import ContentType


# Create your views here.

@login_required
def flight_list(request):
    flights = Flight.objects.all()
    return render(request, 'flight/flight-list.html', {'flights': flights})

@login_required
def flight_detail(request, id):
    flight = get_object_or_404(Flight, pk=id)
    reviews = Review.objects.filter(
        content_type=ContentType.objects.get_for_model(Flight),
        object_id=id
    )
    context = {
        'flight': flight,
        'reviews': reviews
    }

    return render(request, 'flight/flight-detail.html', context)

project4/hotel/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Hotel
from .forms import HotelBookingForm
from review.models import Review
from django.contrib.contenttypes.models import ContentType

@login_required
def hotel_list(request):
    hotels = Hotel.objects.all()
    return render(request, 'hotel/hotel-list.html', {'hotels': hotels})

@login_required
def book_hotel(request, hotel_id):
    hotel = get_object_or_404(Hotel, pk=hotel_id)
    if request.method == 'POST':
        form = HotelBookingForm(request.POST, instance=hotel)
        if form.is_valid():
            form.save()
            return render(request, 'hotel/booking_confirmation.html', {'hotel': hotel})
    else:
        form = HotelBookingForm(instance=hotel)

    return render(request, 'hotel/book_hotel.html', {'form': form, 'hotel': hotel})

@login_required
def hotel_detail(request, id):
    hotel = get_object_or_404(Hotel, pk=id)
    reviews = Review.objects.filter(
        content_type=ContentType.objects.get_for_model(Hotel),
        object_id=id
    )
    context = {
        'hotel': hotel,
        'reviews': reviews
    }
    return render(request, 'hotel/hotel-detail.html', context)

project4/tour/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import TourBookingForm
from .models import Tour
from review.models import Review
from django.contrib.contenttypes.models import ContentType

# Create your views here.

@login_required
def tour_list(request):
    tours = Tour.objects.all()
    return render(request, 'tour/tour-list.html', {'tours': tours})

@login_required
def book_tour(request, tour_id):
    tour = get_object_or_404(Tour, pk=tour_id)
    if request.method == 'POST':
        form = TourBookingForm(request.POST, instance=tour)
        if form.is_valid():
            form.save()
            return render(request, 'tour/booking_confirmation.html', {'tour': tour})
    else:
        form = TourBookingForm(instance=tour)

    return render(request, 'tour/book_tour.html', {'form': form, 'tour': tour})

@login_required
def tour_detail(request, id):
    tour = get_object_or_404(Tour, pk=id)
    reviews = Review.objects.filter(
        content_type=ContentType.objects.get_for_model(Tour),
        object_id=id
    )
    context = {
        'tour': tour,
        'reviews': reviews
    }
    return render(request, 'tour/tour-detail.html', context)

project4/dashboard/templates/partials/dashboard_booking.html
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-box">
                <div class="form-title-wrap">
                    <div class="d-flex align-items-center justify-content-between">
                        <h3 class="title">Booking Results</h3>
                        <div class="select-contain">
                            <select class="select-contain-select"
                                name="status"
                                hx-get="{% url 'dashboard:filter_bookings' %}"
                                hx-trigger="change"
                                hx-target="#booking-results" hx-include="this">
                                <option value="all">Any Status</option>
                                {% for status, status_display in booking_context.booking_status %}
                                <option value="{{ status }}">{{ status_display }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <div class="form-content pb-2" id="booking-results">
                    {% for booking in booking_context.bookings %}
                    <div class="card-item card-item-list card-item--list">
                        <div class="card-body">
                            <div class="d-flex align-items-center">
                                <h3 class="card-title">{{ booking.get_booking_detail }}</h3>
                                <span
                                    class="badge {% if booking.status == 'cancelled' %}badge-danger{% elif booking.status == 'ongoing' %}badge-warning{% elif booking.status == 'completed' %}badge-success{% else %}badge-info{% endif %} ml-2">
                                    {{ booking.status }}</span>
                            </div>
                            <ul class="list-items list-items-2 pt-2 pb-3">
                                <li><span>Start date:</span> {{ booking.reservation_date }}</li>
                                <li><span>End date:</span> {{ booking.reservation_end_date }}</li>
                                <li><span>Booking details:</span> {{ booking.num_of_guests }} People</li>
                                <li><span>Client:</span> {{ booking.traveler_fname }} {{ booking.traveler_lname }}</li>
                                <li><span>Total Amount:</span> ${{ booking.total_amount }}</li>
                            </ul>
                            <div class="btn-box">
                                <a href="#" class="theme-btn theme-btn-small theme-btn-transparent"><i
                                        class="la la-envelope mr-1"></i>Send Message</a>
                            </div>
                        </div>
                        <div class="action-btns">
                            <a href="#" class="theme-btn theme-btn-small mr-2"><i
                                    class="la la-check-circle mr-1"></i>Approve</a>
                            <a href="#" class="theme-btn theme-btn-small"><i class="la la-times mr-1"></i>Cancel</a>
                        </div>
                    </div>
                    {% empty %}
                    <p>No bookings available.</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

project4/dashboard/templates/partials/dashboard_flight.html
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-box">
                <div class="form-title-wrap">
                    <div class="d-flex align-items-center justify-content-between">
                        <div>
                            <h3 class="title">Flight Lists</h3>
                            <p class="font-size-14">Showing detailed flight information.</p>
                        </div>
                        <div class="select-contain">
                            <select name="select" class="select-contain-select" hx-get="{% url 'dashboard:filter_flights' %}" hx-trigger="change" hx-target="#flights-list" hx-indicator="#loading" hx-swap="innerHTML">
                                <option value="1">Any Time</option>
                                <option value="2">Latest</option>
                                <option value="3">Oldest</option>
                            </select>
                            <div id="loading" style="display:none;">Loading...</div>
                        </div>
                    </div>
                </div>
                <div class="form-content">
                    <div class="table-form table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Airline</th>
                                    <th scope="col">Departure City</th>
                                    <th scope="col">Arrival City</th>
                                    <th scope="col">Departure Date</th>
                                    <th scope="col">Departure Time</th>
                                    <th scope="col">Arrival DateTime</th>
                                    <th scope="col">Available Seats</th>
                                    <th scope="col">Fare</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody id="flights-list">
                                {% include 'partials/flights_table.html' %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

project4/dashboard/templates/partials/dashboard_hotel.html
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-box">
                <div class="form-title-wrap">
                    <div class="d-flex align-items-center justify-content-between">
                        <div>
                            <h3 class="title">Hotel Listings</h3>
                            <p class="font-size-14">Browse our comprehensive list of hotels.</p>
                        </div>
                        <div class="select-contain">
                            <select name="select" class="select-contain-select" hx-trigger="change"
                                hx-get="{% url 'dashboard:filter_hotels' %}" hx-target="#hotel-list" hx-swap="innerHTML"
                                hx-indicator="#loading">
                                <option value="1">Any City</option>
                                <option value="2">Highest Rated</option>
                                <option value="3">Most Rooms</option>
                            </select>
                            <div id="loading" style="display:none;">Loading...</div>
                        </div>
                    </div>
                </div>
                <div class="form-content">
                    <div class="table-form table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col">Hotel Name</th>
                                    <th scope="col">City</th>
                                    <th scope="col">Country</th>
                                    <th scope="col">Total Rooms</th>
                                    <th scope="col">Nightly Rate</th>
                                    <th scope="col">Action</th>
                                </tr>
                            </thead>
                            <tbody id="hotel-list">
                                {% include 'partials/hotels_table.html' %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

project4/dashboard/templates/partials/dashboard_review.html
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="form-box">
                <div class="form-title-wrap">
                    <div class="d-flex align-items-center justify-content-between">
                        <div>
                            <h3 class="title">Review Lists</h3>
                            <p class="font-size-14">Showing all entries</p>
                        </div>
                    </div>
                </div>
                <div class="form-content">
                    <div class="comments-list">
                        {% for review in reviews %}
                            <div class="comment">
                                <div class="comment-avatar">
                                    <!-- Assuming you have a method to get the user avatar url -->
                                    <img class="avatar__img" alt="User avatar" src="#">
                                </div>
                                <div class="comment-body">
                                    <div class="meta-data">
                                        <h3 class="comment__author">{{ review.content_object }}</h3>
                                        <div class="meta-data-inner d-flex">
                                            <p class="comment__meta mr-1">By <a href="#">{{ review.user.username }}</a></p>
                                            <span class="ratings d-flex align-items-center mr-1">
                                                {% for i in "12345" %}
                                                    {% if forloop.counter <= review.rating %}
                                                        <i class="la la-star"></i>
                                                    {% else %}
                                                        <i class="la la-star-o"></i>
                                                    {% endif %}
                                                {% endfor %}
                                            </span>
                                            <p class="comment__date">{{ review.review_date|date:"F j, Y" }}</p>
                                        </div>
                                    </div>
                                    <p class="comment-content">
                                        {{ review.comment }}
                                    </p>
                                    <div class="comment-replies">
                                        <!-- Include the review replies here -->
                                        {% include 'partials/review_replies.html' with replies=review.replies.all %}
                                    </div>
                                    <div class="comment-reply">
                                        <button class="theme-btn" type="button" data-bs-toggle="collapse" data-bs-target="#replyForm{{ review.id }}" aria-expanded="false" aria-controls="replyForm{{ review.id }}">
                                            <span class="la la-mail-reply mr-1"></span>Reply
                                        </button>
                                    </div>
        
                                    <!-- Collapsible form area -->
                                    <div class="collapse" id="replyForm{{ review.id }}">
                                        <div class="mt-4">
                                            <form class="form" hx-post="{% url 'dashboard:reply_review' review_id=review.id %}" hx-target="#replyForm{{ review.id }}" hx-swap="innerHTML">
                                                {% csrf_token %}
                                                <input type="hidden" name="review_id" value="{{ review.id }}">
                                                <div class="mb-4">
                                                    <label for="reply-comment{{ review.id }}" class="form-label">Replying to {{ review.user.first_name }}</label>
                                                    <textarea class="form-control" rows="4" name="reply-comment" id="reply-comment{{ review.id }}" placeholder="Enter your reply" required></textarea>
                                                </div>
                                                <button type="submit" class="btn btn-primary">Post Reply</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        {% empty %}
                            <p>No reviews available.</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Pagination and footer could be included here if required -->
</div>

project4/dashboard/templates/partials/hotels_table.html
{% for hotel in hotels %}
<tr>
    <td>{{ hotel.name }}</td>
    <td>{{ hotel.city }}</td>
    <td>{{ hotel.country }}</td>
    <td>{{ hotel.total_rooms }}</td>
    <td>${{ hotel.nightly_rate }}</td>
    <td>
        <div class="table-content">
            <a href="{% url 'hotel:hotel_detail' hotel.id %}" class="theme-btn theme-btn-small mr-2"
                data-toggle="tooltip" data-placement="top" title="View details"><i class="la la-eye"></i></a>
            <a href="#" class="theme-btn theme-btn-small" data-toggle="modal" data-target="#modalPopup"><i
                    class="la la-envelope"></i></a>
        </div>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="6">No hotels available.</td>
</tr>
{% endfor %}

project4/dashboard/templates/partials/user_table.html
{% for user in users %}
<tr>
    <td>{{ user.username }}</td>
    <td>{{ user.first_name }}</td>
    <td>{{ user.last_name }}</td>
    <td>{{ user.email }}</td>
    <td>{{ user.userprofile.street_address }}</td>
    <td>{{ user.userprofile.city }}</td>
    <td>{{ user.userprofile.state }}</td>
    <td>{{ user.userprofile.zipcode }}</td>
    <td>{{ user.userprofile.phone_number }}</td>
    <td>
        <div class="table-content">
            <a hx-get="{% url 'dashboard:user_detail' user_id=user.id %}" hx-target="#user_main_dashboard" hx-swap="innerHTML" class="theme-btn theme-btn-small mr-2" data-toggle="tooltip" data-placement="top"
                title="View details"><i class="la la-eye"></i></a>
            <a href="{% url 'dashboard:user_delete' user_id=user.id %}" class="theme-btn theme-btn-small"><i
                    class="la la-trash"></i></a>
        </div>
    </td>
</tr>
{% empty %}
<tr>
    <td colspan="9">No users available.</td>
</tr>
{% endfor %}