project4/booking/urls.py
from django.urls import path

from . import views

app_name = 'booking'

urlpatterns = [
    path('create/<str:service_type>/<int:service_id>/', views.create_booking, name='create_booking'),
    path('booking/', views.list_booking, name='list-booking'),
    path('detail/<int:booking_id>/', views.detail_booking, name='detail_booking'),
    path('booking/update/<int:booking_id>/', views.update_booking, name='update-booking'),
    # path('deletebooking/', views.delete_booking, name='delete_booking')
]

project4/flight/urls.py
from django.urls import path
from . import views

app_name = 'flight'

urlpatterns = [
    path('', views.flight_list, name='flight_list'),
    path('flight/<int:id>/', views.flight_detail, name='flight_detail'),
]

project4/project4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index
from userprofile.forms import LoginForm
from userprofile.views import signup
from userprofile.views import logout_view


urlpatterns = [
    path('', index, name='index'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', logout_view, name='logout'),
    path('sign-up/', signup, name='signup'),
    path('admin/', admin.site.urls, name='admin'),
    path('userprofile/', include('userprofile.urls')),
    path('flight/', include('flight.urls')),
    path('tour/', include('tour.urls')),
    path('hotel/', include('hotel.urls')),
    path('booking/', include('booking.urls')),
    path('promotion/', include('promotion.urls')),
    path('invoice/', include('invoice.urls')),
    path('payment/', include('payment.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project4/review/urls.py
from django.urls import path
from . import views

app_name = 'review'

urlpatterns = [
    # path('reviews/', views.review_list, name='review_list'),
    # path('reviews/<int:pk>/', views.review_detail, name='review_detail'),
    # path('reviews/add/', views.review_create, name='review_add'),
    # path('reviews/<int:pk>/edit/', views.review_update, name='review_edit'),
    # path('reviews/<int:pk>/delete/', views.review_delete, name='review_delete'),
    path('add-review/<str:service_type>/<int:service_id>/', views.htmx_add_review, name='htmx_add_review'),
]

project4/tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'

urlpatterns = [
    path('', views.tour_list, name='tour_list'),
    path('book/<int:tour_id>/', views.book_tour, name='book_tour'),
    path('detail/<int:id>/', views.tour_detail, name='tour_detail')
]

project4/flight/models.py
from django.db import models
from datetime import datetime, timedelta
# from django.utils.timezone import now


# Create your models here.
class Flight(models.Model):
    airline = models.CharField(max_length=50)
    flight_date = models.DateField()
    flight_time = models.TimeField()
    departure_city = models.CharField(max_length=20)
    arrival_city = models.CharField(max_length=20)
    duration = models.DecimalField(max_digits=4, decimal_places=2)
    total_seats = models.IntegerField()
    booked_seats = models.IntegerField(default=0)     
    fare = models.DecimalField(max_digits=5, decimal_places=2)

    def calculate_arrival_datetime(self):
        # Convert duration to a timedelta
        # Note: duration is assumed to be in hours
        duration_hours = int(self.duration)
        duration_minutes = int((self.duration - duration_hours) * 60)
        duration_td = timedelta(hours=duration_hours, minutes=duration_minutes)

        # Combine the flight_date and flight_time into a datetime
        departure_datetime = datetime.combine(self.flight_date, self.flight_time)

        # Calculate the arrival datetime
        arrival_datetime = departure_datetime + duration_td
        return arrival_datetime
    
    def available_seats(self):
        """Returns the number of available seats on the flight."""
        return self.total_seats - self.booked_seats
    
    def __str__(self):
        return f'{self.airline} Flight from {self.departure_city} to {self.arrival_city}'

project4/flight/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Flight
from review.models import Review
from django.contrib.contenttypes.models import ContentType


# Create your views here.

@login_required
def flight_list(request):
    flights = Flight.objects.all()
    return render(request, 'flight/flight-list.html', {'flights': flights})

@login_required
def flight_detail(request, id):
    flight = get_object_or_404(Flight, pk=id)
    reviews = Review.objects.filter(
        content_type=ContentType.objects.get_for_model(Flight),
        object_id=id
    )
    context = {
        'flight': flight,
        'reviews': reviews
    }

    return render(request, 'flight/flight-detail.html', context)

project4/flight/templates/flight/flight-detail.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Globetrekker Flight - Detail{% endblock %}
{% block content %}
<section class="pt-7 pb-5 d-flex align-items-end dark-overlay bg-cover"
    style="background-image: url('{% static 'img/photo/flight-wallpaper.jpeg' %}');">
    <div class="container overlay-content">
        <div class="d-flex justify-content-between align-items-start flex-column flex-lg-row align-items-lg-end">
            <div class="text-white mb-4 mb-lg-0">
                <div class="badge badge-pill badge-transparent px-3 py-2 mb-4"><a
                        href="{% url 'flight:flight_list' %}">Flights</a></div>
                <h1 class="text-shadow verified">{{ flight.airline }}</h1>
                <p><i class="fa-map-marker-alt fas me-2"></i>{{ flight.arrival_city }} </p>
                <p class="mb-0 d-flex align-items-center"><i class="fa fa-xs fa-star text-primary"></i><i
                        class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i
                        class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-gray-200 me-4"> </i>8
                    Reviews</p>
            </div>
            <div class="calltoactions"><a class="btn btn-primary" href="#leaveReview"
                    onclick="$('#leaveReview').collapse('show')" data-smooth-scroll>Leave a Review</a>
                    <a class="btn btn-primary" href="{% url 'booking:create_booking' service_type='flight' service_id=flight.id %}">Book this flight</a>
                </div>
        </div>
    </div>
</section>
<section class="py-6">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <!-- About Listing-->
                <div class="text-block">
                    <h3 class="mb-3">About</h3>
                    <p class="text-muted"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                        reprehenderit in voluptate velit esse cillum dolore.</p>
                    <p class="text-muted"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                        exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                        reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
                        occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
                <div class="text-block">
                    <!-- Listing Location-->
                    <h3 class="mb-4">Flight Map</h3>
                    <div class="map-wrapper-300 mb-3">
                        <div class="h-100" id="detailMap"></div>
                    </div>
                </div>
                <div class="text-block">
                    <!-- Gallery-->
                    <h3 class="mb-4">Gallery</h3>
                    <div class="row gallery ms-n1 me-n1">
                        <div class="col-lg-4 col-6 px-1 mb-2"><a href="{% static 'img/photo/AA1.jpeg' %}"><img
                                    class="img-fluid" src="{% static 'img/photo/AA1.jpeg' %}" alt="..."></a></div>
                        <div class="col-lg-4 col-6 px-1 mb-2"><a href="{% static 'img/photo/AA2.jpeg' %}"><img
                                    class="img-fluid" src="{% static 'img/photo/AA2.jpeg' %}" alt="..."></a></div>
                        <div class="col-lg-4 col-6 px-1 mb-2"><a href="{% static 'img/photo/AA3.jpeg' %}"><img
                                    class="img-fluid" src="{% static 'img/photo/AA3.jpeg' %}" alt="..."></a></div>
                        <div class="col-lg-4 col-6 px-1 mb-2"><a href="{% static 'img/photo/AA4.jpeg' %}"><img
                                    class="img-fluid" src="{% static 'img/photo/AA4.jpeg' %}" alt="..."></a></div>
                        <div class="col-lg-4 col-6 px-1 mb-2"><a href="{% static 'img/photo/AA5.jpeg' %}"><img
                                    class="img-fluid" src="{% static 'img/photo/AA5.jpeg' %}" alt="..."></a></div>
                        <div class="col-lg-4 col-6 px-1 mb-2"><a href="{% static 'img/photo/AA6.jpeg' %}"><img
                                    class="img-fluid" src="{% static 'img/photo/AA6.jpeg' %}" alt="..."></a></div>
                    </div>
                </div>
                
                <div class="text-block">
                    <p class="subtitle text-sm text-primary">Reviews </p>
                    <h5 class="mb-4">Listing Reviews </h5>
                    <div id="reviews-container">
                        {% include 'partials/htmx_add_review.html' %}
                    </div>
                    <div class="py-5">
                        <button class="btn btn-outline-primary" type="button" data-bs-toggle="collapse"
                            data-bs-target="#leaveReview" aria-expanded="false" aria-controls="leaveReview">Leave a
                            review</button>
                        <div class="collapse mt-4" id="leaveReview">
                            <h5 class="mb-4">Leave a review</h5>
                            <form class="form" id="contact-form"
                                hx-post="{% url 'review:htmx_add_review' service_type='flight' service_id=flight.id %}"
                                hx-target="#reviews-container" hx-trigger="submit">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="mb-4">
                                            <label for="rating" class="form-label">Your rating *</label>
                                            <select class="form-select focus-shadow-0" name="rating" id="rating">
                                                <option value="5">&#9733;&#9733;&#9733;&#9733;&#9733; (5/5)</option>
                                                <option value="4">&#9733;&#9733;&#9733;&#9733;&#9734; (4/5)</option>
                                                <option value="3">&#9733;&#9733;&#9733;&#9734;&#9734; (3/5)</option>
                                                <option value="2">&#9733;&#9733;&#9734;&#9734;&#9734; (2/5)</option>
                                                <option value="1">&#9733;&#9734;&#9734;&#9734;&#9734; (1/5)</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-4">
                                    <label for="comment" class="form-label">Review text *</label>
                                    <textarea class="form-control" rows="4" name="comment" id="comment"
                                        placeholder="Enter your review" required></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary">Post review</button>
                            </form>

                        </div>
                    </div>

                </div>
            </div>
            <div class="col-lg-4">
                <div class="text-block">
                    <h3 class="mb-4">Flight Amenities</h3>
                    <ul class="amenities-list list-inline">
                        <li class="list-inline-item mb-3">
                            <div class="d-flex align-items-center">
                                <div class="icon-circle bg-secondary me-2"><i class="fa fa-wifi"></i></div>
                                <span>In-flight WiFi</span>
                            </div>
                        </li>
                        <li class="list-inline-item mb-3">
                            <div class="d-flex align-items-center">
                                <div class="icon-circle bg-secondary me-2"><i class="fa fa-utensils"></i></div>
                                <span>Meal service (including special dietary menus)</span>
                            </div>
                        </li>
                        <li class="list-inline-item mb-3">
                            <div class="d-flex align-items-center">
                                <div class="icon-circle bg-secondary me-2"><i class="fa fa-glass-martini"></i></div>
                                <span>Alcoholic and non-alcoholic beverages</span>
                            </div>
                        </li>
                        <li class="list-inline-item mb-3">
                            <div class="d-flex align-items-center">
                                <div class="icon-circle bg-secondary me-2"><i class="fa fa-ban"></i></div>
                                <span>No smoking on all flights</span>
                            </div>
                        </li>
                        <li class="list-inline-item mb-3">
                            <div class="d-flex align-items-center">
                                <div class="icon-circle bg-secondary me-2"><i class="fa fa-film"></i></div>
                                <span>In-flight entertainment systems</span>
                            </div>
                        </li>
                        <li class="list-inline-item mb-3">
                            <div class="d-flex align-items-center">
                                <div class="icon-circle bg-secondary me-2"><i class="fa fa-charging-station"></i></div>
                                <span>USB and power outlets</span>
                            </div>
                        </li>
                        <li class="list-inline-item mb-3">
                            <div class="d-flex align-items-center">
                                <div class="icon-circle bg-secondary me-2"><i class="fa fa-suitcase-rolling"></i></div>
                                <span>Extra legroom and adjustable seats in select classes</span>
                            </div>
                        </li>
                        <li class="list-inline-item mb-3">
                            <div class="d-flex align-items-center">
                                <div class="icon-circle bg-secondary me-2"><i class="fa fa-baby-carriage"></i></div>
                                <span>Special assistance for families and children</span>
                            </div>
                        </li>
                    </ul>
                </div>

            </div>
        </div>
    </div>
</section>

{% endblock %}

project4/flight/templates/flight/flight-list.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Globetrekker Flights{% endblock %}
{% block content %}
<div class="container mt-5">
  <h2 class="mb-4">Available Flights</h2>
  <div class="row">
    {% for flight in flights %}
    <div class="col-md-6 col-xl-4 mb-5">
      <div class="card h-100 border-0 shadow">
        <div class="card-body">
          <h5 class="card-title">{{ flight.airline }}</h5>
          <h6 class="text-muted">{{ flight.flight_date  }} at {{ flight.flight_time  }}</h6>
          <div class="d-flex justify-content-between my-3">
            <span class="badge bg-primary">Departure: {{ flight.departure_city }}</span>
            <span class="badge bg-success">Arrival: {{ flight.arrival_city }}</span>
          </div>
          <div class="my-2">
            <i class="fas fa-clock"></i> Duration: {{ flight.duration }} hours
          </div>
          <div class="my-2">
            <i class="fas fa-chair"></i> Seats available: {{ flight.total_seats }}
          </div>
          <div class="my-2">
            <i class="fas fa-tag"></i> Fare: ${{ flight.fare }}
          </div>
          <a href="{% url 'booking:create_booking' service_type='flight' service_id=flight.id %}"
            class="btn btn-primary mt-3">Book now</a>
            <a href="{% url 'flight:flight_detail' id=flight.id %}"
            class="btn btn-primary mt-3">Detail</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}