project4/invoice/urls.py
from django.urls import path
from . import views

app_name = 'invoice'

urlpatterns = [
    path('', views.invoice_list, name='invoice_list'),
    path('invoice-detail/<int:invoice_id>', views.invoice_detail, name='invoice-detail'),
]

project4/payment/urls.py
from django.urls import path
from .views import make_payment

app_name = 'payment'

urlpatterns = [
    path('payment/<int:invoice_id>/', make_payment, name='make_payment'),
]


# from django.urls import path
# from . import views

# app_name = 'invoice'

# urlpatterns = [
#     path('', views.invoice_list, name='invoice_list'),
#     path('invoice-detail/<int:invoice_id>', views.invoice_detail, name='invoice-detail'),
# ]

project4/project4/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index
from userprofile.forms import LoginForm
from userprofile.views import signup
from userprofile.views import logout_view


urlpatterns = [
    path('', index, name='index'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', logout_view, name='logout'),
    path('sign-up/', signup, name='signup'),
    path('admin/', admin.site.urls, name='admin'),
    path('userprofile/', include('userprofile.urls')),
    path('flight/', include('flight.urls')),
    path('tour/', include('tour.urls')),
    path('hotel/', include('hotel.urls')),
    path('booking/', include('booking.urls')),
    path('promotion/', include('promotion.urls')),
    path('invoice/', include('invoice.urls')),
    path('payment/', include('payment.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('review/', include('review.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project4/tour/urls.py
from django.urls import path
from . import views

app_name = 'tour'

urlpatterns = [
    path('', views.tour_list, name='tour_list'),
    path('book/<int:tour_id>/', views.book_tour, name='book_tour'),
    path('detail/<int:id>/', views.tour_detail, name='tour_detail')
]

project4/userprofile/urls.py
from django.urls import path

from . import views

app_name = 'userprofile'

urlpatterns = [
    path('myaccount/', views.myaccount, name='myaccount'),
    path('editprofile/', views.editprofile, name='editprofile'),
    path('changepassword/', views.change_password, name='changepassword'),
    path('list-users/', views.list_users, name='list_users'),
]

project4/invoice/models.py
from django.db import models
from django.conf import settings
from django.db import models

class Invoice(models.Model):
    booking_date = models.DateField()
    booking = models.OneToOneField('booking.Booking', on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    promotion = models.ForeignKey('promotion.Promotion', on_delete=models.SET_NULL, null=True, blank=True)
    total_amount = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f"Invoice {self.id}"
    
    # def remaining_balance(self):
    #     total_paid = sum(payment.amount for payment in self.payment_set.all())
    #     return max(self.total_amount - total_paid, 0)

project4/invoice/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Invoice
from booking.models import Booking
from promotion.models import Promotion
from django.utils import timezone


# Create your views here.
@login_required
def invoice_list(request):
    invoices = Invoice.objects.filter(user=request.user, total_amount__gt=0).order_by('-booking_date')
    return render(request, 'invoice/invoice-list.html', {'invoices': invoices})

@login_required
def invoice_detail(request, invoice_id):
    invoice = get_object_or_404(Invoice, id=invoice_id)
    return render(request, 'invoice/invoice-detail.html', {'invoice':invoice})

project4/invoice/templates/invoice/already_exitsts.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Globetrekker Invoices{% endblock %}
{% block content %}
<div class="container mt-5">
  <div class="row">
      <div class="col-md-12">
          <div class="alert alert-warning" role="alert">
              <h4 class="alert-heading">Invoice Already Exists!</h4>
              <p>{{ message }}</p>
              <hr>
              <p class="mb-0">Please check the existing invoice or contact support for further assistance.</p>
          </div>
      </div>
  </div>
</div>
{% endblock %}

project4/invoice/templates/invoice/invoice-detail.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Globetrekker Invoices{% endblock %}
{% block content %}
<section class="py-5 p-print-0">
  <div class="container">
    <div class="row mb-4 d-print-none">
      <div class="col-lg-6">
        <!-- Breadcrumbs -->
        <ol class="breadcrumb ps-0 justify-content-start">
          <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'userprofile:myaccount' %}">Account</a></li>
          <li class="breadcrumb-item"><a href="{% url 'invoice:invoice_list' %}">All invoices</a></li>
          <li class="breadcrumb-item active">Invoice {{ invoice.id }} </li>
        </ol>
      </div>
      <div class="col-lg-6 text-lg-end">
        <button class="btn btn-primary me-2"><i class="far fa-file-pdf me-2"></i> Download PDF</button>
        <button class="btn" onclick="window.print()"><i class="fas fa-print me-2"></i> Print</button>
      </div>
    </div>
    <div class="card border-0 shadow shadow-print-0">
      <div class="card-header bg-gray-100 p-5 border-0 px-print-0">
        <div class="row">
          <div class="col-6 d-flex align-items-center"><img src="{% static 'img/logo.svg' %}" alt="Directory"></div>
          <div class="col-6 text-end">
            <h3 class="mb-0">Invoice {{ invoice.id }}</h3>
            <p class="mb-0">Issued on {{ invoice.booking_date|date:"M d, Y" }}</p>
          </div>
        </div>
      </div>
      <div class="card-body p-5 p-print-0">
        <div class="row mb-4">
          <div class="col-sm-6 pe-lg-3">
            <h2 class="h6 text-uppercase mb-4">Travel Company</h2>
            <h6 class="mb-1">Globetrekker</h6>
            <p class="text-muted">13/25 New Avenue<br>New Heaven<br>45Y 73J<br>England<br><strong>Great Britain</strong>
            </p>
          </div>
          <div class="col-sm-6 ps-lg-4">
            <h2 class="h6 text-uppercase mb-4">Customer</h2>
            <h6 class="mb-1">{{ invoice.user.first_name }} {{ invoice.user.last_name }}</h6>
            <p class="text-muted">{{ invoice.user.userprofile.street_address }},</p>
            <p class="text-muted">{{ invoice.user.userprofile.city }}, {{ invoice.user.userprofile.state }}, {{ invoice.user.userprofile.zipcode }} </p>
          </div>
        </div>
        <div class="row mb-5">
          <div class="col-md-6 pe-lg-3 text-sm">
            <div class="row">
              <div class="col-6 text-uppercase text-muted">Booking ID</div>
              <div class="col-6 text-end">{{ invoice.booking.id }}</div>
            </div>
            <div class="row">
              <div class="col-6 text-uppercase text-muted">Payment method</div>
              <div class="col-6 text-end">Credit card</div>
            </div>
          </div>
          <div class="col-md-6 ps-lg-4 text-sm">
            <div class="row">
              <div class="col-6 text-uppercase text-muted">Issued on</div>
              <div class="col-6 text-end">{{ invoice.booking_date|date:"M d, Y" }}</div>
            </div>
            <div class="row">
              <div class="col-6 text-uppercase text-muted">Due on</div>
              <div class="col-6 text-end">{{ invoice.booking_date|date:"M d, Y" }}</div>
            </div>
          </div>
        </div>
        <div class="table-responsive text-sm mb-5">
          <table class="table table-striped">
            <thead class="bg-gray-200">
              <tr class="border-0">
                <th class="center">#</th>
                <th>Item</th>
                <th>Description</th>
                <th class="text-end">Price</th>
                <th class="center">Qty</th>
                <th class="text-end">Total</th>
              </tr>
            </thead>
            <tbody>
              {% if invoice.booking.flight %}
              <tr>
                <td class="text-center">1</td>
                <td class="fw-bold">Flight</td>
                <td>{{ invoice.booking.flight.departure }} to {{ invoice.booking.flight.arrival_city }}</td>
                <td class="text-end">{{ invoice.booking.flight.fare|floatformat:2 }}</td>
                <td class="text-center">{{ invoice.booking.num_of_guests }}</td>
                <td class="text-end">{% widthratio invoice.booking.num_of_guests 1 invoice.booking.flight.fare %}</td>
              </tr>
              {% endif %}
              {% if invoice.booking.hotel %}
              <tr>
                <td class="text-center">2</td>
                <td class="fw-bold">Hotel</td>
                <td>{{ invoice.booking.hotel.description }}</td>
                <td class="text-end">{{ invoice.booking.hotel.nightly_rate|floatformat:2 }}</td>
                <td class="text-center">{{ invoice.booking.duration }}</td>
                <td class="text-end">{% widthratio invoice.booking.hotel.nightly_rate 1 invoice.booking.duration %}</td>
              </tr>
              {% endif %}
              {% if invoice.booking.tour %}
              <tr>
                <td class="text-center">3</td>
                <td class="fw-bold">Tour</td>
                <td>{{ invoice.booking.tour.description }}</td>
                <td class="text-end">{{ invoice.booking.tour.price|floatformat:2 }}</td>
                <td class="text-center">{{ invoice.booking.num_of_guests }}</td>
                <td class="text-end">{% widthratio invoice.booking.tour.price 1 invoice.booking.num_of_guests %}</td>
              </tr>
              {% endif %}
            </tbody>
          </table>
        </div>
        <div class="row">
          <div class="col-sm-7 col-lg-5 col-xl-4 ms-auto">
            <table class="table">
              <tbody>
                <tr class="text-sm">
                  <td class="fw-bold">Subtotal</td>
                  <td class="text-end">${{ invoice.booking.total_amount}}</td>
                </tr>
                <tr class="text-sm">
                  {% if invoice.promotion %}
                  <td class="fw-bold">Discount</td>
                  <td class="text-end">{{ invoice.promotion.discount_percentage|floatformat:2 }}%</td>
                  {% else %}
                  <td class="fw-bold">Discount</td>
                  <td class="text-end">Promo code invalid</td>
                  {% endif %}
                </tr>
                <tr>
                  <td class="text-uppercase fw-bold">Total</td>
                  <td class="text-end fw-bold">${{ invoice.total_amount }}</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer bg-gray-100 p-5 px-print-0 border-0 text-end text-sm">
          <p class="mb-0">Thank you for your business. Globetrekker.</p>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

project4/invoice/templates/invoice/invoice-list.html
{% extends "core/base.html" %}
{% load static %}
{% block title %}Globetrekker Invoices{% endblock %}
{% block content %}
<div class="container mt-5">
  <h2 class="mb-4">Your Invoices</h2>
  <div class="row">
    {% for invoice in invoices %}
    <div class="col-md-6 col-xl-4 mb-5">
      <div class="card h-100 border-0 shadow">
        <div class="card-body">
          <h5 class="card-title">Invoice ID: {{ invoice.id }}</h5>
          <h6 class="text-muted">Booking Date: {{ invoice.booking_date }}</h6>
          <div class="my-3">
            <span class="badge bg-primary">Total Amount: ${{ invoice.total_amount }}</span>
          </div>
          <!-- More details can go here -->
          <a href="{% url 'invoice:invoice-detail' invoice_id=invoice.id %}" class="btn btn-primary mt-3">View Details</a>
          <a href="{% url 'payment:make_payment' invoice_id=invoice.id %}" class="btn btn-primary mt-3">Pay now</a>
        </div>
      </div>
    </div>
    {% empty %}
    <div class="col-12">
      <p class="text-muted mb-5">You have no invoices</p>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}